# ‘hello world’
print("hello world")

print("Hallo, world")

print('First Line', end=' ')
print('Second Line', end='\n\n\n')
print('Third Line', end='!')

print('Third Line', end='\t')
print('Third Line')

print('#########')
print('#', end='\t')
print('#')
print('#', end='\t')
print('#')
print('#', end='\t')
print('#')
print('#', end='\t')
print('#')
print('#', end='\t')
print('#')
print('#########')

print('#', end='\t')
print('#')
print('#', end='\t')
print('#')
print('#', end='\t')
print('#')
print('#########')
print('#', end='\t')
print('#')
print('#', end='\t')
print('#')
print('#', end='\t')
print('#')